version: '3'

services:
  webapp:
    build: ./
    depends_on:
      - database
    links:
      - database
    privileged: true
    user: root
    volumes:
      #Swap the folder path for plugin vs theme development
      - ../:/var/www/html
  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: app
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ChangeMe
      POSTGRES_USER: symfony
      PGDATA: /tmp
    ports:
      - 5432:5432
    volumes:
      #- db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      - pgdata:/var/lib/postgresql/data
      ###< doctrine/doctrine-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  pgdata: ###< doctrine/doctrine-bundle ###
  webapp:
